tenants:
  datasource: '{tenant1:
  {username:"postgres", password:"password", url:"jdbc:postgresql://localhost:5432/tenant1", driver:"org.postgresql.Driver"},
  tenant2:
  {username:"postgres", password:"password", url:"jdbc:postgresql://localhost:5432/tenant2", driver:"org.postgresql.Driver"}
  }'
axon:
  axonserver:
    enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    client-id: userservice
    producer:
      event-processor-mode: subscribing
    consumer:
      event-processor-mode: subscribing
  distributed:
    enabled: true
  serializer:
    messages: jackson
    events: jackson
    general: jackson
logging:
  level:
    org:
      apache:
        kafka: INFO
kafka:
  topics: accounts, users
  publish-topic: users
